name: Secret Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  secret-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run secret check
        run: ./.githooks/check-secrets --all
